"""add_db_log

Revision ID: c7af4524a5fe
Revises: 9d0b1ca6ce82
Create Date: 2021-05-11 20:01:23.731550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7af4524a5fe'
down_revision = '9d0b1ca6ce82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['influenserul.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='influenserul'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_log', schema='influenserul')
    # ### end Alembic commands ###
